# Generated by Django 3.0.5 on 2020-04-20 22:10

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Huis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naam', models.CharField(max_length=35)),
            ],
        ),
        migrations.CreateModel(
            name='Huisgenoot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naam', models.CharField(max_length=20)),
                ('brakcounter', models.PositiveSmallIntegerField()),
                ('laatst_brak', models.DateTimeField(default=django.utils.timezone.now)),
                ('huis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BrakApp.Huis')),
            ],
        ),
    ]
